### ISSUE TITLE
better keyboard support

### ISSUE THREAD

**Issue by ssj71** [rbdrum2midi/rbdrum2midi#1]
somebody else created a similar windows driver, could give insight on the operation of wii keyboard.
https://github.com/martinjos/rb3_driver/blob/master/rb3_driver.c

**Comment by randomas** [comment]
Might be worth writing to them and seeing if they're interested in
merging the projects, get one package for both win and lin. 

Il 28/12/2015 18:57, ssj71 ha scritto:

**Comment by janifr** [comment]
Should someone create a roadmap for further development? There might be some great ideas to make this (and Martins's) project even more useful. What I have in my mind is a multiplatform GUI and configurable actions for the keyboard. For example mapping pitch bend to some other controller, transposition, and maybe creating series of pitch bend events simulating the gargle effect trick of a real guitar with a floating bridge.

What if we fork a new project with name rbinstruments for example? Would it be better to use this code as a base or Martin's?

**Comment by randomas** [comment]
I'm all for it, I've always wanted to ad a simple multiplatform gui (pygtk,
qt?) with a simple wav trigger to play around without having to go through
all the midi mapping... Unfortunately I barely have time to look into
things anymore which is why I'm gratefull other people have interest in the
project too.

Matt.
Il 29/dic/2015 07:13, "janifr" notifications@github.com ha scritto:

**Comment by ssj71** [comment]
well, I think as is we've got good support for the drumkits and partial support for guitars and keyboards now (which I don't think will be oft-used features). Since it seems none of us have a lot of time I think we'll close this issue and try to focus on just supporting users as they report issues. Feel free to re-open if you oppose.
