### ISSUE TITLE
Harmonix Drumkit PSIII/Wii compatible

### ISSUE THREAD

**Issue by Franr** [rbdrum2midi/rbdrum2midi#4]
Hey guys, amazing work here. Tried it with my drumkit but didn't work.

from `lsusb`
```
Bus 002 Device 003: ID 1bad:0005 Harmonix Music 
```

The same issue than here: https://github.com/rbdrum2midi/rbdrum2midi/issues/2
Checking the code, there is no mapping for `0x0005` product id.
Tried changing it on the wii one, but then:
```
claimed interface
init_capture failed.
```
Almost! haha

P.D: the drum have 4 pads, a pedal, and a Wii/PS3 switch on its back.

**Comment by randomas** [comment]
Have you tried switching it to ps3?
does the lsusb change change if you do? 
Have you tried the -rb1 option?

**Comment by randomas** [comment]
Hmm I suspect there's more than one Wii kit version ...

**Comment by Franr** [comment]
Switching it to ps3 changed the id to 0210 (PS3, good) but failed with a `init_capture failed`.
Also tried with the -rb1 flag, the same.

**Comment by Franr** [comment]
The error on the init_capture is -1 (IO error)

**Comment by randomas** [comment]
To use rbdrum2midi without root priviledges create a rules file in /etc/udev/rules.d/

file 90-drumkit.rules:

SUBSYSTEM=="usb", ATTR{idVendor}=="12ba", ATTR{idProduct}=="0210", GROUP="audio", MODE="0664"
SUBSYSTEM=="usb", ATTR{idVendor}=="12ba", ATTR{idProduct}=="0120", GROUP="audio", MODE="0664"
SUBSYSTEM=="usb", ATTR{idVendor}=="1bad", ATTR{idProduct}=="0003", GROUP="audio", MODE="0664"
SUBSYSTEM=="usb", ATTR{idVendor}=="1bad", ATTR{idProduct}=="0005", GROUP="audio", MODE="0664"
SUBSYSTEM=="usb", ATTR{idVendor}=="1bad", ATTR{idProduct}=="3110", GROUP="audio", MODE="0664"

Otherwise you should try to running it as root see if it still gives the same mistake, try it both in wii and ps3 mode, with and without the -rb1 option with the -dbg option so you can test pads in case it does work. (in wii mode try it with your code patch for the libusb code). 

Good luck!

**Comment by ssj71** [comment]
@Franr any update on this issue? I just pushed an update that should theoretically make it work in WII mode.

**Comment by Franr** [comment]
Sorry but don't have the wii drums with me anymore. Will close the issue.

**Comment by ssj71** [comment]
ok thanks for the update!
